### PR TITLE
add new examples testing webgl texturing

### PR DESCRIPTION
**Pull request by brupelo**

### CODE REVIEW

**Comment by mikolalysenko** [comment]
You should add in the get-pixels and save-pixels dependencies to package.json.  To do this, you can do:  `npm i -S get-pixels save-pixels`

**Comment by brupelo** [comment]
Strange, i had done that few days ago, redoing again

**Comment by brupelo** [comment]
Ok, the current status on windows is just 2 fails, they happen on rendering.js:

⨯ rendering_point-no-attributes
  not ok 507 getError expected: NO_ERROR. Was INVALID_OPERATION :
    ---
      operator: fail
    ...
  not ok 508 should be 0,255,0,255
    ---
      operator: fail
    ...
  DEBUG: at (0, 0) expected: 0,255,0,255 was 0,0,0,0

**Comment by brupelo** [comment]
All tests passing on windows right now, ready to go!

**Comment by andresiraola** [comment]
I tried this but it is not working.. or wasn't actually..

gl.texImage2D expects an ImageData or in fact, any object with: width, height and data. 

The problem is that get-pixels returns and object where width and height are in fact shape[0] and shape[1] so to fix the problem I just did:

```
image.width = image.shape[0];
image.height = image.shape[1];
```

before calling gl.texImage2D.

Is it working for you? Am I missing something?

**Comment by brupelo** [comment]
@andresiraola Hi! Thanks for the comment, yeah, you're right... that did the trick, i've added a new commit fixing example\webgl_fundamentals\test3.jpg , now you can display lena. Awesome.

**Comment by brupelo** [comment]
@mikolalysenko Hi, why is the PR taking so long to be merged? I hope the project won't die and become unmaintained cos is promising ;-)

**Comment by dfcreative** [comment]
@brupelo hm, is it possible to make appveyor succeed at tests?

**Comment by brupelo** [comment]
@dfcreative , Mmm, no clue, good question actually. 

I know @mikolalysenko has already looked at that few weeks ago but not sure what's the status of that right now. About the PR, before pushing I'm making sure all tests are correct doing # npm test and testing manually each example.

PS: Right now conformance tests showed are 53730/53730 , all ok so far.

**Comment by mikolalysenko** [comment]
No, it isn't broken or unmaintained.  I just had to switch gears to catch up on some other work.  I'll pick this up again once I have a block of time to concentrate on it.

**Comment by brupelo** [comment]
@mikolalysenko I've updated my fork and checked all is working correctly on the windows version. I've tested the whole thing from scratch and it is working flawlessly (building, examples & tests). So, could you accept this PR? I don't understand why it's taking ages to be accepted. Is there anything wrong with the PR? If so, please let me know.

Regards

**Comment by mikolalysenko** [comment]
Previously it wasn't passing the CI tests, which made it difficult to integrate.  I'll take another look and if it is all good, I'll merge it in.

**Comment by brupelo** [comment]
I give up :) . It discourages quite a lot to continue contributing to this great project when the PRs take that much (opened PR 30 march and today is 08 July) to be merged to master. One little advice, even if the library is great per-se but the community (contributors or apps on top of it) is not growing the project will take ages to become mature. IMHO the library should be attractive to the general public and not being only used for a very small set of use-cases.

My 2 cents, good luck!

**Pull request closed without merging**
