### PR TITLE
Update prebuild to v5.1.2

### PR DESCRIPTION
**Pull request by jas99**
This is to address issue #92

### CODE REVIEW

**Comment by mourner** [comment]
@mikolalysenko would love to see this land! Will save us a lot of time waiting for `gl` to rebuild. The test failure seems to be unrelated to the upgrade (it also fails on master).

**Comment by jas99** [comment]
@mourner yup its failing on the master
https://ci.appveyor.com/project/jas99/headless-gl  

cc @mikolalysenko

**Comment by ibgreen** [comment]
@mikolalysenko Would also love to see this published (without this gl adds 2 minutes to every yarn install that would otherwise take 5 seconds...)

(I believe that I have merge permissions in this repo, but it's moot since I couldn't publish).

**Comment by presmini** [comment]
this will save me a ton of time. +1!

**Pull request merged**
