### PR TITLE
OES_texture_float support

### PR DESCRIPTION
**Pull request by begmec**
Adds OES_texture_float support to headless-gl

### CODE REVIEW

**Comment by begmec** [comment]
I fixed the formatting errors and got some additional OpenGL-conformance issues. I will try to fix them when there is some time.

**Comment by mourner** [comment]
@begmec awesome, thanks for working on that! BTW, would also be open to adding [OES_texture_half_float](https://developer.mozilla.org/en-US/docs/Web/API/OES_texture_half_float), or would that be better left fro a different PR?

**Comment by begmec** [comment]
@mourner welcome :) probably a different PR. I have to see if I have time left for this.

**Comment by begmec** [comment]
There is still one conformance issue open:
On 
gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.LINEAR);
the texture "completeness" of float textures should fail.
Any ideas on how to achieve this properly?

**Comment by dhritzkiv** [comment]
Unsure, without spending lots of time diving into the tests.

However, it seems like there is more than just one issue in the conformance test, no?

**Comment by begmec** [comment]
To me it looks like that only the texture completeness issue is left. It produces several errors if you look into the conformance tests. If fixed, everything should work.

**Comment by begmec** [comment]
There are still some issues left regarding "texParameteri".

**Comment by begmec** [comment]
locally all test are passing on my machine now.

does anybody know why we get this error here:

# alpha texture
not ok 5 no plan found
⨯ fail  1
?

**Comment by dhritzkiv** [comment]
No idea why the tests instantly fail on CI.

My tests are ultimately failing locally, on the negative level test in the more_functions_copyTexImage2DBadArgs test group, strangely.

That being said, the float-texture tests seem to be passing locally.

**Comment by dhritzkiv** [comment]
It looks like a feature I added over a year ago suffered from the same problem in CI: #121

**Comment by begmec** [comment]
@dhritzkiv Thanks!
@mourner @dhritzkiv When will you merge the branch into the trunk?

**Comment by dhritzkiv** [comment]
Re-ran the tests locally on another machine and everything passes. Merging.

**Pull request merged**
