### PR TITLE
added test of compositing postprocessing effects

### PR DESCRIPTION
**Pull request by dphil**
I'm helping @bhouston at ExoCortex investigate a bug using headless-gl. This PR includes a test of the output of postprocessing passes (utilizing threejs) which does not succeed. A single render pass outputs a white box as expected, but for some reason simply adding a copy shader pass after it results in no box (black background). A similar non-headless test rendering to a browser displays the white box in both tests (as expected), leading us to think it could be an issue with headless-gl and not threejs.

### CODE REVIEW

**Comment by mikolalysenko** [comment]
The problem is most likely due to copyTexImage2D not working correctly.  Fixing that is still on my todo list.  As a work around you could use a framebuffer object instead and it should work.

Can you try trimming this PR down a bit?  It would be easier to debug without digging through all of THREE.js.  Ideally the test case should be completely self contained.

**Comment by bhouston** [comment]
Hi @mikolalysenko, Unfortunately copyTexImage2D is not used in this code path in ThreeJS.  It is actually only used in the ThreeJS LensFlarePlugin and no where else.  We'll look into this further.

**Comment by bhouston** [comment]
> Can you try trimming this PR down a bit? It would be easier to debug without digging through all of THREE.js. Ideally the test case should be completely self contained.

This is really an integration test:

https://en.wikipedia.org/wiki/Integration_testing

My thoughts is to keep the ThreeJS stuff to ensure that headless-gl works end-to-end with a complex system.  But we should aim to create specific bug reproductions as well so that we can debug the individual issues.

**Comment by mikolalysenko** [comment]
Based on [this PR](https://github.com/mrdoob/three.js/pull/9107), it looks like the problem is in THREE.js so I'm going to close this issue.

**Pull request closed without merging**
