### PR TITLE
FIX #166 const let and precheck framebuffer status high cpu

### LINKED ISSUE #166: Modernization of lib?
I'm curious what thoughts are on moving constructors into their own files, as classes, some cleanup, and adding semicolons?

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
This PR:
* Modernizes the library with `let`, `const`, and `class`es
* Offers performance improvements using easier to follow methods calls (`this.method()`) and inherited (`super.method()`) in favor of using `method.call(this)`
* Organizes extensions and static properties
* Cleans up the API for easier to understand organization

### CODE REVIEW

**Comment by dhritzkiv** [comment]
Amazing! I'll review this in the next couple of days

**Comment by robertleeplummerjr** [comment]
Ty sir.

**Comment by robertleeplummerjr** [comment]
Don't leave me hangin' ;)

**Comment by dhritzkiv** [comment]
Looks great! Sorry it took me so long to review it - been busy busy busy.

I'll merge this ASAP. Do you you think it's a good idea for me to cut a release, or do you have other modernization plans?

If I cut a release, I'll likely do so as a semver minor one.

**Comment by robertleeplummerjr** [comment]
>Do you you think it's a good idea for me to cut a release, or do you have other modernization plans?

No more as of this moment, I think you'll do, or did, what was best.

**Pull request merged**
