### PR TITLE
use prebuild --install and --all

### PR DESCRIPTION
**Pull request by ralphtheninja**
* Using `prebuild --install` will download prebuilt binaries only when installing from npm and compile otherwise, so when developing locally (git clone) the code will be compiled and also if you're using this module as a git+ dependency.
* Removed `.prebuildrc` because you can do `prebuild --all` now to build for all targets, see https://github.com/mafintosh/prebuild/blob/3d5b4faa4fd6fd5cb48c14d7c84bf4ca208235aa/targets.js for details (this will be updated on patch releases)

### CODE REVIEW

**Comment by ralphtheninja** [comment]
ping @mikolalysenko :)

**Comment by mikolalysenko** [comment]
Nice!  I need to figure out why the circleCI test failed.

@ralphtheninja if you are interested in it, would you like to be added as an admin on this project?

**Comment by ralphtheninja** [comment]
> @ralphtheninja if you are interested in it, would you like to be added as an admin on this project?

I have access already and can merge :)

**Comment by ralphtheninja** [comment]
@mikolalysenko Maybe circleCI did use prebuild to download prebuilts and now when it has to build it fails? I did a quick check and it might be related to an old `gyp` on the system. Just guessing though.

**Comment by ralphtheninja** [comment]
Let me add a `prebuild --install --verbose` just to get some more information. We can always remove that commit later.

**Comment by mikolalysenko** [comment]
Thanks!

**Pull request merged**
