### PR TITLE
README.md xvfb-run documentation

### PR DESCRIPTION
**Pull request by bsergean**
Here's a PR to add some documentation about Linux headless server setup to the README file

Some time ago I had managed to change the commit id of the angle submodule but I cannot revert that, so the PR has an additional file that I don't know how to remove ... creating it anyway.

### CODE REVIEW

**Comment by bsergean** [comment]
Also this PR has almost all my history of messing up with the build procedure and contains many commits. I don't really know how to rebase this ...

**Comment by mikolalysenko** [comment]
Thanks, I'll take a look at it and clean up/rebase later.

**Comment by mikolalysenko** [comment]
Hmm...  There is a lot of stuff in this PR.  Can you just cherry-pick the documentation relevant bits and send a clean PR?

**Comment by bsergean** [comment]
Created new clean PR here -> https://github.com/stackgl/headless-gl/pull/41

I'm closing this one.

**Pull request closed without merging**
